name: Build And Push Container Images
on:
  push:
    branches:
      - publish
jobs:
  build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${REPOSITORY}:${TAG}
        env:
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.sha }}
      - name: Push
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${REPOSITORY}:${TAG}
        env:
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.sha }}
      - name: Login
        run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${OWNER} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
      - name: Push
        run: docker push ghcr.io/${REPOSITORY}:${TAG}
        env:
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.sha }}

